### ISSUE TITLE
Test Framework Research

### ISSUE THREAD

**Issue by ImpulseChimp** [ImpulseChimp/ImpulseEngine#6]
Need to find a good test framework for c++ that has what we need.

Started research here.
https://en.wikipedia.org/wiki/List_of_unit_testing_frameworks#C.2B.2B

**Comment by ImpulseChimp** [comment]
#### Necessary Features 
- Test Fixtures
- Unit/Integration Support
- 

#### Bonus Features
- Mocking Support (Would be nice, but not a deal breaker)

**Comment by userpoth** [comment]
Are you considering Google Test? I'm not exactly sure what all the features do as this is the first I'm reading about unit testing, but it supports fixtures and mocks and it's free.

**Comment by ImpulseChimp** [comment]
@userpoth I haven't looked too much at Google Tests yet, but it keeps coming up from most of the places I am looking at other test frameworks. I also just looked at the wikipedia info for it above and it actually fits most of the criteria I have.

**Comment by ImpulseChimp** [comment]
@userpoth 
#### Google Test Pros
- Fixtures
- Mocks
- Templates
- Exceptions
- Clean Syntax
- Actively maintained (https://github.com/google/googletest)

#### Cons
- Compiled
- Possible dependencies off of Python for integration testing

All in all, it looks like a really good option. Compared to most of the other frameworks I have looked at, Boost & CxxTest, Google Test seems to be overall better balanced. It also has the backing of being Google owned and maintained which speaks a lot to its quality.

**Note:** Since it is compiled, it may be a bit more work to maintain/run. I have nothing against this since we can write simple scripts if need be to run test packages, but it is good to be aware of. Header only libraries are a shiny alternative since they are dirt easy to run and maintain, but they also have less features. Just something to think about.
